name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
    - title: "🚀 What's new"
      labels:
          - 'PR: New'
    - title: '🏋️ Improvements'
      labels:
          - 'PR: Improvement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'PR: Fix'
exclude-labels:
    - 'PR: No Changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    minor:
        labels:
            - 'minor'
    patch:
        labels:
            - 'patch'
    default: patch
template: |
    ## What Changed

    $CHANGES
    ## Development
    **Date** 23/06/2023
    **Ticket ID**[#CCN-23] File upload download Issue
    **Description** Added @lazy annotation and Changed code according to keyType in storeFile method
    
    ## DevOps Details
    
    **Date** 23/06/2023
    **Environment** PRE-PRD
    **Customized jar to be Deployed** Adapter
    **Customization Jar name** AdapterCustomization.jar
    **Updated By** @demo
