categories:
  - title: 'Melhorias'
    labels:
      - 'enhancement'
  - title: 'Correções'
    label: 'bug'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: 'patch'
template: |
  ## Changelog da versão: $RESOLVED_VERSION

  $CHANGES

  Commits: [LINK DO SEU REPO]/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  Tag: [LINK DO SEU REPO]/releases/tag/v$RESOLVED_VERSION
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
