name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  
  $CHANGES
  
  ## Development Task
  
  **Date** 23/06/2023
  **Ticket ID**[#CCN-I1550] File upload download Issue
  **Description** Added @lazy annotation and Changed code according to keyType in storeFile method
  
  ## DevOps Details
  
  **Date** 23/06/2023
  **Environment** PRE-PRD
  **Customized jar to be Deployed** Adapter
  **Customization Jar name** AdapterCustomization.jar
  **Updated By** @YusufTinwala 
