name: Generete release from milestone
## hay
on:
  push: 
    branches: main
  workflow_dispatch:
    inputs:
      milestone:
        description: "v1.0"
        required: true
      version:
        description: "Version to be released"
        required: true

jobs:
  generate-release:
    name: Generete release from milestone
    runs-on: ubuntu-latest
    steps:
      - name: Relese notes format
        uses: Beakyn/gha-format-release-notes@v1
        id: format
        env:
          GITHUB_TOKEN: "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"
        with:
          # required
          repository: ${{ github.repository }}
          milestone: 1

          # optional
          custom-row: "${issue.number} <--> ${issue.title}"
          custom-group-by-label: |
            [
              {
                "title": "### Feature 🎉",
                "labels": ["feature"]
              },
              {
                "title": "### Bug Fixes 🐛",
                "labels": ["bug"]
              },
              {
                "title": "### Refactor & Improvements ✨",
                "labels": ["enhancement", "refactor", "chore"]
              }
            ]

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: "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"
        with:
          tag_name: newsd
          release_name: Fdsd
          body: .github/release.yml
          draft: false
          prerelease: false

      - name: Close milestone
        uses: Beakyn/gha-close-milestone@master
        env:
          GITHUB_TOKEN: "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"
        with:
          # required
          repository: ${{ github.repository }}
          milestone: ${{ github.event.inputs.milestone }}
