name: Create release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create tag
        id: tag
        run: echo "TAG=5.0.${{ github.run_number }}" >> $GITHUB_ENV
      - name: Push tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
    outputs:
      output1: ${{ env.TAG + 1 }}

  release:
    runs-on: ubuntu-22.04
    permissions: write-all
    needs: tag
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{needs.tag.outputs.output1}}
        run: gh release create --prerelease "$tag" --repo="$GITHUB_REPOSITORY" --title="v${tag#v}"  --generate-notes
