name: Create release

on:
  pull_request:
    tags:
      - v*
    branches:
      - main

jobs:
  update_release_draft:
    permissions: write-all
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
      - name: CreateNotes
        run: gh release create --repo="$GITHUB_REPOSITORY" --generate-notes
