name: RELEASE DRAFTER
on:
  push:
    branches:
      - main
jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Drafting new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
