name: Create release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
## AutoTag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: echo "TAG=v1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
