name: Create release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
    ## demossww
  release:
    permissions: write-all
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:         
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${tag#v}" --generate-notes  --notes-file=https://github.com/shekharsuthar/demo/blob/ee6a4f8b26e9b289270adcaaca1da8cd325584bf/same.txt
