name: Create release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  release:
    permissions: write-all
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:         
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.repository.updated_at }}
          
        run: gh release create "$tag"  --repo="$GITHUB_REPOSITORY" --title="${{ steps.date.outputs.date }}" --generate-notes
