name: Create release

on:
  push:
    tags:
      - v*
    branches:
      - main



jobs:
  update_release_draft:
    permissions: write-all
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:

      - name: "Generate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${tag#v}" --generate-notes
